#!/bin/bash

PROCSPAWN_COMMANDQUEUE=()

procspawn_queue() {
  PROCSPAWN_COMMANDQUEUE[${#PROCSPAWN_COMMANDQUEUE[*]}]=$1
}
procspawn_start() {
  PROCSPAWN_NUMPROCS=2
  PROCSPAWN_DELAY=.1
  if [ ! -z $1 ]; then
    PROCSPAWN_NUMPROCS=$1
  fi
  if [ ! -z $2 ]; then
    PROCSPAWN_DELAY=$2
  fi
  PROCSPAWN_CURRPROCS=0
  PROCSPAWN_ALLPROCS=


  trap 'if [ $PROCSPAWN_CURRPROCS -gt 0 ]; then echo; echo -n "Killing processes:"; for I in $PROCSPAWN_ALLPROCS; do echo -n " $I"; kill $I; done; echo " done"; exit 1; fi' SIGINT
  trap 'PROCSPAWN_NUMPROCS=$(( $PROCSPAWN_NUMPROCS + 1 )); echo "Increased NUMPROCS to ${PROCSPAWN_NUMPROCS}"' SIGUSR1
  trap 'PROCSPAWN_NUMPROCS=$(( $PROCSPAWN_NUMPROCS - 1 )); echo "Decreased NUMPROCS to ${PROCSPAWN_NUMPROCS}"' SIGUSR2


  for idx in ${!PROCSPAWN_COMMANDQUEUE[*]}; do
    PROCSPAWN_CMD=${PROCSPAWN_COMMANDQUEUE[$idx]}
    unset PROCSPAWN_COMMANDQUEUE[$idx]
    while [ $PROCSPAWN_CURRPROCS -ge $PROCSPAWN_NUMPROCS ]; do
      PROCSPAWN_STILLRUNNING=
      PROCSPAWN_STILLRUNNINGCNT=0
      for PROCSPAWN_PID in $PROCSPAWN_ALLPROCS; do
        if [ -e /proc/$PROCSPAWN_PID ]; then
          PROCSPAWN_STILLRUNNING="$PROCSPAWN_STILLRUNNING $PROCSPAWN_PID"
          PROCSPAWN_STILLRUNNINGCNT=$(( $PROCSPAWN_STILLRUNNINGCNT + 1 ))
        fi
      done
      if [ "$PROCSPAWN_ALLPROCS" = "$PROCSPAWN_STILLRUNNING" ]; then
        sleep $PROCSPAWN_DELAY
      else
        PROCSPAWN_ALLPROCS=$PROCSPAWN_STILLRUNNING
        PROCSPAWN_CURRPROCS=$PROCSPAWN_STILLRUNNINGCNT
      fi
    done

    sh -c "$PROCSPAWN_CMD" &
    PROCSPAWN_NEWPID=$!
    #echo "Spawned '$CMD' ($NEWPID)"
    PROCSPAWN_ALLPROCS="$PROCSPAWN_ALLPROCS $PROCSPAWN_NEWPID"
    PROCSPAWN_CURRPROCS=$(( $PROCSPAWN_CURRPROCS + 1 ))
  done
  wait
  PROCSPAWN_ALLPROCS=
  PROCSPAWN_CURRPROCS=0
  #trap '' SIGINT SIGUSR1 SIGUSR2
}
